# fly.toml app configuration file generated for echohacks-blue-brook-5925 on 2024-10-13T15:09:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echohacks'
primary_region = 'sea'

[build]
[build.args]
GO_VERSION = '1.23.0'

[env]
PORT = '22'

[[mounts]]
source = "sshkeys"
destination = "/.ssh"


[[services]]
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ['app']
internal_port = 22
protocol = "tcp"
[[services.ports]]
port = 22


[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
